const ADMINS={
 "VFA-OWNER":{id:"VFA-OWNER",password:"VFAOwner2026!",name:"School Owner",role:"Owner / Administrator",department:"Administration"},
 "VFA-ASSISTANT":{id:"VFA-ASSISTANT",password:"VFAAssist2026!",name:"School Assistant",role:"Assistant Administrator",department:"Administration"},
 "VFA-JONATHAN":{id:"VFA-JONATHAN",password:"VFAJonathan2026!",name:"Jonathan Gombay",role:"Administrator",department:"Administration"}
};
const gradeList=["Kindergarten",...Array.from({length:9},(_,i)=>`Grade ${i+1}`)], subjects=["Mathematics","English Language","Science","Social Studies","ICT","Biology","Chemistry","Physics"], periods={first:["1st Period","2nd Period","3rd Period","Exam"],second:["4th Period","5th Period","6th Period","Exam"]};
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},$=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const VERSION="admin-v3";if(localStorage.getItem("vfaPortalDataVersion")!==VERSION){["vfaAdminStudents","vfaAdminPayments","vfaExams","vfaAdminAnnouncements","vfaGrades","vfaScaleResponses","vfaAssignments","vfaSuggestions","vfaTeacherRecords","vfaTeacherAttendance","loggedInStudent"].forEach(k=>localStorage.removeItem(k));localStorage.setItem("vfaPortalDataVersion",VERSION)}
let students=get("vfaAdminStudents",[]),payments=get("vfaAdminPayments",[]),exams=get("vfaExams",[]),announcements=get("vfaAdminAnnouncements",[]),gradesData=get("vfaGrades",{}),scaleResponses=get("vfaScaleResponses",[]),assignments=get("vfaAssignments",[]),suggestions=get("vfaSuggestions",[]),teacherRecords=get("vfaTeacherRecords",[]),teacherAttendance=get("vfaTeacherAttendance",[]),currentAdmin=null;
function save(){localStorage.setItem("vfaAdminStudents",JSON.stringify(students));localStorage.setItem("vfaAdminPayments",JSON.stringify(payments));localStorage.setItem("vfaExams",JSON.stringify(exams));localStorage.setItem("vfaAdminAnnouncements",JSON.stringify(announcements));localStorage.setItem("vfaGrades",JSON.stringify(gradesData));localStorage.setItem("vfaScaleResponses",JSON.stringify(scaleResponses));localStorage.setItem("vfaAssignments",JSON.stringify(assignments));localStorage.setItem("vfaSuggestions",JSON.stringify(suggestions));localStorage.setItem("vfaTeacherRecords",JSON.stringify(teacherRecords));localStorage.setItem("vfaTeacherAttendance",JSON.stringify(teacherAttendance))}
function loginAdmin(){const id=$("staffId").value.trim().toUpperCase(),p=$("staffPassword").value,a=ADMINS[id];if(!a||a.password!==p){$("loginMessage").textContent="Incorrect Admin ID or password.";return}currentAdmin={...a};$("loginView").classList.add("hidden");$("adminApp").classList.remove("hidden");renderIdentity();init()}
$("staffLoginForm").onsubmit=e=>{e.preventDefault();loginAdmin()};$("toggleStaffPassword").onclick=()=>$("staffPassword").type=$("staffPassword").type==="password"?"text":"password";$("staffLogout").onclick=()=>location.reload();
function renderIdentity(){$("staffPill").textContent=`${currentAdmin.name} • ${currentAdmin.role}`;$('staffGreeting').textContent=`Welcome, ${currentAdmin.name}`;$('todayLabel').textContent=new Date(today()+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});$('profileName').textContent=currentAdmin.name;$('profilePosition').textContent=currentAdmin.role;$('profileId').textContent=currentAdmin.id;$('profileDepartment').textContent=currentAdmin.department}
const titles={overview:"Home",students:"Students",grades:"Grades",tuition:"Financial Records",assignments:"Assignments",announcements:"Announcements",exams:"Examination Timetable",scale:"Parent Feedback",suggestions:"Admin Suggestions",teachers:"Staff / Teacher Attendance",profile:"Profile"};
function openSection(id){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('sectionTitle').textContent=titles[id];window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>openSection(b.dataset.section));
function init(){renderStats();setupStudents();setupGrades();setupTuition();setupAssignments();setupAnnouncements();setupExams();setupScale();setupSuggestions();setupTeachers()}
function renderStats(){$('statStudents').textContent=students.filter(s=>s.status!=="Inactive").length;$('statTeachers').textContent=teacherRecords.length;$('statContent').textContent=assignments.length+announcements.length+exams.length+suggestions.length}
function nextId(){let n=students.length+1;while(students.some(s=>s.id===`VFA-STU-${String(n).padStart(4,'0')}`))n++;return `VFA-STU-${String(n).padStart(4,'0')}`}
function setupStudents(){const filter=$('studentClassFilter');filter.innerHTML='<option value="All">All Classes</option>'+gradeList.map(g=>`<option>${g}</option>`).join('');$('addStudentBtn').onclick=()=>editStudent('');$('studentSearch').oninput=renderStudents;filter.onchange=renderStudents;renderStudents()}
function renderStudents(){const q=$('studentSearch').value.toLowerCase(),f=$('studentClassFilter').value;const list=students.filter(s=>(f==='All'||s.grade===f)&&(!q||`${s.name} ${s.id}`.toLowerCase().includes(q)));$('studentRows').innerHTML=list.map(s=>`<tr><td>${esc(s.id)}</td><td><strong>${esc(s.name)}</strong></td><td>${esc(s.grade)}</td><td>${esc(s.parent)}</td><td>${s.loginId?'<span class="success">Assigned</span>':'<span class="muted">Not assigned</span>'}</td><td>${esc(s.status||'Active')}</td><td><button class="icon-btn" onclick="editStudent('${esc(s.id)}')">✏️</button></td></tr>`).join('')||'<tr><td colspan="7">No students registered yet.</td></tr>'}
window.editStudent=id=>{const s=students.find(x=>x.id===id)||{id:nextId(),name:'',grade:'',parent:'',loginId:'',password:'',status:'Active'};openModal(id?'Edit Student':'Add Student',`<form id="studentForm" class="form-grid"><label>Student ID<input name="id" value="${esc(s.id)}" readonly></label><label>Full Name<input name="name" value="${esc(s.name)}" required></label><label>Class<select name="grade" required><option value="">Select class</option>${gradeList.map(g=>`<option ${s.grade===g?'selected':''}>${g}</option>`).join('')}</select></label><label>Parent / Guardian<input name="parent" value="${esc(s.parent)}"></label><label>Class Teacher<input name="teacher" value="${esc(s.teacher)}"></label><label>School Year<input name="schoolYear" value="${esc(s.schoolYear)}" placeholder="e.g. 2026–2027"></label><label>Conduct / Report Note<input name="conduct" value="${esc(s.conduct)}"></label><label>Portal Login ID<input name="loginId" value="${esc(s.loginId)}" placeholder="e.g. VFA-STU-0001" required></label><label>Portal Password<input name="password" value="${esc(s.password)}" placeholder="Assign a password" required></label><label>Status<select name="status"><option ${s.status!=='Inactive'?'selected':''}>Active</option><option ${s.status==='Inactive'?'selected':''}>Inactive</option></select></label><div class="submit-row"><button class="primary" type="submit">Save Student</button></div></form>`);$('studentForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const i=students.findIndex(x=>x.id===f.id);if(i>=0)students[i]={...students[i],...f};else students.push({...f,tuition:{total:0,paid:0,balance:0},payments:[],attendance:[],teacher:''});save();closeModal();init();alert('Student record saved.')}}
function setupGrades(){$('gradeClass').innerHTML=gradeList.map(g=>`<option>${g}</option>`).join('');$('gradeSubject').innerHTML=subjects.map(s=>`<option>${s}</option>`).join('');$('gradeSemester').onchange=updatePeriods;$('gradePeriod').onchange=renderGradeRows;$('gradeClass').onchange=renderGradeRows;$('gradeSubject').onchange=renderGradeRows;$('gradeSearch').oninput=renderGradeRows;$('saveAllGrades').onclick=saveGrades;updatePeriods()}
function updatePeriods(){$('gradePeriod').innerHTML=periods[$('gradeSemester').value].map(p=>`<option>${p}</option>`).join('');renderGradeRows()}
function gradeKey(id){return `${id}|${$('gradeSubject').value}|${$('gradePeriod').value}`}
function renderGradeRows(){const cls=$('gradeClass').value,q=$('gradeSearch').value.toLowerCase(),list=students.filter(s=>s.grade===cls&&s.status!=='Inactive'&&(!q||`${s.name} ${s.id}`.toLowerCase().includes(q)));$('gradeEntryRows').innerHTML=list.map(s=>{const k=gradeKey(s.id),v=gradesData[k]??'';return `<tr><td>${esc(s.id)}</td><td>${esc(s.name)}</td><td><input class="grade-input" data-id="${esc(s.id)}" value="${esc(v)}" type="number" min="0" max="100"></td><td>${v!==''?'<span class="success">Saved</span>':'<span class="muted">Not entered</span>'}</td></tr>`}).join('')||'<tr><td colspan="4">No students are registered in this class yet.</td></tr>'}
function saveGrades(){document.querySelectorAll('.grade-input').forEach(i=>{const v=i.value.trim(),k=gradeKey(i.dataset.id);if(v==='')delete gradesData[k];else gradesData[k]=Math.max(0,Math.min(100,Number(v)))});save();renderGradeRows();alert('Grades saved successfully.')}
function setupTuition(){$('feeStudent').innerHTML=students.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — ${esc(s.id)}</option>`).join('');$('feeStudent').onchange=renderTuitionCard;$('addPayment').onclick=addPayment;renderTuitionCard();renderFees()}
function renderTuitionCard(){const s=students.find(x=>x.id===$('feeStudent').value);$('feeDue').value=s?.tuition?.total??'';const paid=s?.tuition?.paid??0;$('tuitionCard').innerHTML=s?`<strong>${esc(s.name)}</strong><p>Total fees: ${s.tuition?.total??0} • Paid: ${paid} • Balance: ${(s.tuition?.total??0)-paid}</p>`:''}
function addPayment(){const s=students.find(x=>x.id===$('feeStudent').value),due=Number($('feeDue').value||0),amt=Number($('feeAmount').value||0),period=$('feePeriod').value.trim();if(!s||due<0||amt<0||!period)return alert('Complete the financial record fields.');s.tuition=s.tuition||{total:0,paid:0,balance:0};s.tuition.total=due;s.tuition.paid=(s.tuition.paid||0)+amt;s.tuition.balance=Math.max(0,due-s.tuition.paid);payments.unshift({id:Date.now(),studentId:s.id,studentName:s.name,period,amount:amt,date:today()});save();$('feeAmount').value='';$('feePeriod').value='';renderTuitionCard();renderFees();alert('Financial record saved.')}
function renderFees(){$('feeRows').innerHTML=payments.map(p=>{const s=students.find(x=>x.id===p.studentId),bal=s?.tuition?.balance??0;return `<tr><td>${esc(p.date)}</td><td>${esc(p.studentName)}</td><td>${esc(p.period)}</td><td>${esc(p.amount)}</td><td>${esc(bal)}</td><td>${bal<=0?'<span class="success">Paid</span>':'<span class="warning">Balance</span>'}</td><td><button class="icon-btn" onclick="removePayment(${p.id})">🗑️</button></td></tr>`}).join('')||'<tr><td colspan="7">No financial records yet.</td></tr>'}window.removePayment=id=>{payments=payments.filter(p=>p.id!==id);save();renderFees()}
function setupAttendance(){$('attendanceClass').innerHTML=gradeList.map(g=>`<option>${g}</option>`).join('');$('attendanceClass').onchange=refreshAttendanceStudents;$('saveAttendance').onclick=saveAttendance;$('attendanceDate').value=today();refreshAttendanceStudents();renderAttendance()}
function refreshAttendanceStudents(){const c=$('attendanceClass').value;$('attendanceStudent').innerHTML=students.filter(s=>s.grade===c&&s.status!=='Inactive').map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}
function saveAttendance(){const id=$('attendanceStudent').value,s=students.find(x=>x.id===id);if(!s)return alert('Select a student.');attendanceRecords=attendanceRecords.filter(r=>!(r.studentId===id&&r.date===$('attendanceDate').value));attendanceRecords.push({id:Date.now(),studentId:id,studentName:s.name,grade:s.grade,date:$('attendanceDate').value,status:$('attendanceStatus').value});save();renderAttendance()}
function renderAttendance(){$('attendanceRows').innerHTML=attendanceRecords.sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.studentName)}</td><td>${esc(r.grade)}</td><td>${esc(r.status)}</td><td><button class="icon-btn" onclick="removeAttendance(${r.id})">🗑️</button></td></tr>`).join('')||'<tr><td colspan="5">No attendance records yet.</td></tr>'}window.removeAttendance=id=>{attendanceRecords=attendanceRecords.filter(r=>r.id!==id);save();renderAttendance()}
function setupAssignments(){$('assignmentClass').innerHTML='<option value="All Students">All Students</option>'+gradeList.map(g=>`<option>${g}</option>`).join('');$('addAssignment').onclick=addAssignment;renderAssignments()}
function addAssignment(){const x={id:Date.now(),grade:$('assignmentClass').value,subject:$('assignmentSubject').value.trim(),due:$('assignmentDue').value,title:$('assignmentTitle').value.trim(),body:$('assignmentBody').value.trim(),date:today()};if(!x.title||!x.body||!x.subject||!x.due)return alert('Complete the assignment fields.');assignments.unshift(x);save();['assignmentSubject','assignmentDue','assignmentTitle','assignmentBody'].forEach(id=>$(id).value='');renderAssignments();renderStats()}
function renderAssignments(){$('assignmentAdminList').innerHTML=assignments.map(a=>`<div class="announcement-item"><div><strong>${esc(a.title)}</strong><span>${esc(a.subject)} • ${esc(a.grade)} • Due ${esc(a.due)}</span><p>${esc(a.body)}</p></div><button class="icon-btn" onclick="removeAssignment(${a.id})">🗑️</button></div>`).join('')||'<p class="muted">No assignments published yet.</p>'}window.removeAssignment=id=>{assignments=assignments.filter(a=>a.id!==id);save();renderAssignments();renderStats()}
function setupAnnouncements(){$('announcementDate').value=today();$('addAnnouncement').onclick=addAnnouncement;renderAnnouncements()}
function addAnnouncement(){const x={id:Date.now(),title:$('announcementTitle').value.trim(),date:$('announcementDate').value,audience:$('announcementAudience').value,body:$('announcementBody').value.trim()};if(!x.title||!x.date||!x.body)return alert('Complete the announcement.');announcements.unshift(x);save();$('announcementTitle').value='';$('announcementBody').value='';renderAnnouncements();renderStats()}
function renderAnnouncements(){$('announcementAdminList').innerHTML=announcements.map(a=>`<div class="announcement-item"><div><strong>${esc(a.title)}</strong><span>${esc(a.date)} • ${esc(a.audience)}</span><p>${esc(a.body)}</p></div><button class="icon-btn" onclick="removeAnnouncement(${a.id})">🗑️</button></div>`).join('')||'<p class="muted">No announcements published yet.</p>'}window.removeAnnouncement=id=>{announcements=announcements.filter(a=>a.id!==id);save();renderAnnouncements();renderStats()}
function setupExams(){$('examGrade').innerHTML=gradeList.map(g=>`<option>${g}</option>`).join('');$('addExam').onclick=addExam;renderExams()}
function addExam(){const x={id:Date.now(),grade:$('examGrade').value,date:$('examDate').value,subject:$('examSubject').value.trim(),time:$('examTime').value.trim(),room:$('examRoom').value.trim()};if(!x.date||!x.subject||!x.time||!x.room)return alert('Complete the examination fields.');exams.push(x);save();['examDate','examSubject','examTime','examRoom'].forEach(id=>$(id).value='');renderExams();renderStats()}
function renderExams(){$('examAdminRows').innerHTML=exams.map(x=>`<tr><td>${esc(x.grade)}</td><td>${esc(x.date)}</td><td>${esc(x.subject)}</td><td>${esc(x.time)}</td><td>${esc(x.room)}</td><td><button class="icon-btn" onclick="removeExam(${x.id})">🗑️</button></td></tr>`).join('')||'<tr><td colspan="6">No examinations published yet.</td></tr>'}window.removeExam=id=>{exams=exams.filter(x=>x.id!==id);save();renderExams();renderStats()}
function setupScale(){renderScale()};function renderScale(){$('scaleRows').innerHTML=scaleResponses.sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.studentName)}</td><td>${esc(r.parent)}</td><td>${esc((r.answers||[]).join(', '))}</td><td>${esc(r.notes)}</td></tr>`).join('')||'<tr><td colspan="5">No parent feedback has been submitted yet.</td></tr>'}
function setupSuggestions(){$('suggestionTarget').innerHTML='<option value="All Students">All Students</option>'+students.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — ${esc(s.id)}</option>`).join('');$('addSuggestion').onclick=addSuggestion;renderSuggestions()}
function addSuggestion(){const x={id:Date.now(),target:$('suggestionTarget').value,title:$('suggestionTitle').value.trim(),body:$('suggestionBody').value.trim(),date:today(),from:currentAdmin.name};if(!x.title||!x.body)return alert('Complete the suggestion.');suggestions.unshift(x);save();$('suggestionTitle').value='';$('suggestionBody').value='';renderSuggestions();renderStats()}
function renderSuggestions(){$('suggestionAdminList').innerHTML=suggestions.map(s=>`<div class="announcement-item"><div><strong>${esc(s.title)}</strong><span>${esc(s.date)} • To: ${esc(s.target)} • From: ${esc(s.from)}</span><p>${esc(s.body)}</p></div><button class="icon-btn" onclick="removeSuggestion(${s.id})">🗑️</button></div>`).join('')||'<p class="muted">No suggestions published yet.</p>'}window.removeSuggestion=id=>{suggestions=suggestions.filter(s=>s.id!==id);save();renderSuggestions();renderStats()}
function setupTeachers(){$('teacherAttendanceDate').value=today();$('teacherAttendanceDate').onchange=renderTeacherAttendance;$('addTeacher').onclick=addTeacher;renderTeacherAttendance();renderTeacherList()}
function addTeacher(){const name=$('teacherName').value.trim(),position=$('teacherDepartment').value.trim();if(!name||!position)return alert('Enter the staff member name and position.');teacherRecords.push({id:Date.now(),name,position});save();$('teacherName').value='';$('teacherDepartment').value='';renderTeacherAttendance();renderTeacherList();renderStats()}
function renderTeacherAttendance(){const d=$('teacherAttendanceDate').value||today();$('teacherAttendanceDateTitle').textContent=new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('teacherAttendanceRows').innerHTML=teacherRecords.map(t=>{const r=teacherAttendance.find(x=>x.teacherId===t.id&&x.date===d);return `<tr><td>${esc(t.name)}</td><td>${esc(t.position)}</td><td>${r?esc(r.status):'<span class="muted">Not marked</span>'}</td><td>${esc(r?.time||'—')}</td><td><button class="secondary" onclick="markTeacher(${t.id},'Present')">Present</button> <button class="secondary" onclick="markTeacher(${t.id},'Absent')">Absent</button></td></tr>`}).join('')||'<tr><td colspan="5">No staff members added yet.</td></tr>'}
window.markTeacher=(id,status)=>{const d=$('teacherAttendanceDate').value||today(),i=teacherAttendance.findIndex(x=>x.teacherId===id&&x.date===d),r={teacherId:id,date:d,status,time:status==='Present'?new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''};if(i>=0)teacherAttendance[i]=r;else teacherAttendance.push(r);save();renderTeacherAttendance()};function renderTeacherList(){$('teacherRows').innerHTML=teacherRecords.map(t=>`<tr><td>${esc(t.name)}</td><td>${esc(t.position)}</td><td><button class="icon-btn" onclick="removeTeacher(${t.id})">🗑️</button></td></tr>`).join('')||'<tr><td colspan="3">No staff members added yet.</td></tr>'}window.removeTeacher=id=>{teacherRecords=teacherRecords.filter(t=>t.id!==id);teacherAttendance=teacherAttendance.filter(r=>r.teacherId!==id);save();renderTeacherAttendance();renderTeacherList();renderStats()}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}window.closeModal=closeModal;$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
(function(){const menu=$('mobileMenu'),sidebar=document.querySelector('.sidebar'),overlay=$('sidebarOverlay');if(!menu)return;function close(){sidebar.classList.remove('mobile-open');overlay.classList.remove('show');menu.setAttribute('aria-expanded','false')}menu.onclick=()=>{const o=sidebar.classList.toggle('mobile-open');overlay.classList.toggle('show',o);menu.setAttribute('aria-expanded',String(o))};overlay.onclick=close;sidebar.querySelectorAll('button').forEach(b=>b.addEventListener('click',close))})();
