const STAFF={id:"ADMIN001",password:"VFAadmin123"};
const defaultStudents=[
{id:"0020172(001)",name:"Andrew Johnson",grade:"Grade 10",section:"A",parent:"Mary Johnson",status:"Active",schoolYear:"2026–2027",teacher:"Mrs. Sarah Johnson",tuitionTotal:1200,tuitionPaid:800,attendance:{present:129,absent:6}},
{id:"0020172(002)",name:"Jonathan Gombay",grade:"Grade 10",section:"A",parent:"Samuel Gombay",status:"Active",schoolYear:"2026–2027",teacher:"Mrs. Sarah Johnson",tuitionTotal:1200,tuitionPaid:1000,attendance:{present:132,absent:3}},
{id:"0020172(003)",name:"Michael Smith",grade:"Grade 9",section:"B",parent:"Helen Smith",status:"Active",schoolYear:"2026–2027",teacher:"Mr. David Cooper",tuitionTotal:1100,tuitionPaid:700,attendance:{present:127,absent:8}},
{id:"0020172(004)",name:"Sarah Williams",grade:"Grade 11",section:"A",parent:"James Williams",status:"Active",schoolYear:"2026–2027",teacher:"Mrs. Linda Doe",tuitionTotal:1300,tuitionPaid:1300,attendance:{present:134,absent:1}}
];
const key="vfaAdminStudents";let students=JSON.parse(localStorage.getItem(key)||"null")||defaultStudents;
const payments=JSON.parse(localStorage.getItem("vfaAdminPayments")||"[]");
const attendanceRecords=JSON.parse(localStorage.getItem("vfaAttendance")||"[]");
const exams=JSON.parse(localStorage.getItem("vfaExams")||"null")||[
{grade:"Grade 10",section:"A",date:"2026-10-12",subject:"Mathematics",time:"9:00 AM – 11:00 AM",room:"Room 4"},
{grade:"Grade 10",section:"A",date:"2026-10-14",subject:"English Language",time:"9:00 AM – 11:00 AM",room:"Room 4"},
{grade:"Grade 10",section:"A",date:"2026-10-16",subject:"Biology",time:"1:00 PM – 3:00 PM",room:"Science Lab"}
];
const announcements=JSON.parse(localStorage.getItem("vfaAdminAnnouncements")||"null")||[
{title:"Parents and Students Meeting",date:"2026-09-20",body:"Parents and students are reminded about the upcoming school meeting in the main hall."},
{title:"School Field Trip Registration",date:"2026-09-15",body:"Registration is now open for the upcoming school field trip."}
];
function save(){localStorage.setItem(key,JSON.stringify(students));localStorage.setItem("vfaAdminPayments",JSON.stringify(payments));localStorage.setItem("vfaAttendance",JSON.stringify(attendanceRecords));localStorage.setItem("vfaExams",JSON.stringify(exams));localStorage.setItem("vfaAdminAnnouncements",JSON.stringify(announcements));}
function $(id){return document.getElementById(id)}
const loginView=$("loginView"),adminApp=$("adminApp");
$("toggleStaffPassword").onclick=()=>{const p=$("staffPassword");const show=p.type==="password";p.type=show?"text":"password";$("toggleStaffPassword").textContent=show?"🙈":"👁"};
$("staffLoginForm").onsubmit=e=>{e.preventDefault();if($("staffId").value.trim()===STAFF.id&&$("staffPassword").value.trim()===STAFF.password){sessionStorage.setItem("vfaStaffLoggedIn","1");showApp()}else $("loginMessage").textContent="Incorrect staff ID or password."};
function showApp(){loginView.classList.add("hidden");adminApp.classList.remove("hidden");renderAll()}if(sessionStorage.getItem("vfaStaffLoggedIn"))showApp();
$("staffLogout").onclick=()=>{sessionStorage.removeItem("vfaStaffLoggedIn");location.reload()};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>openSection(b.dataset.section));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>openSection(b.dataset.go));
function openSection(id){document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.section===id));$("sectionTitle").textContent={overview:"Dashboard",students:"Students",grades:"Report Cards",tuition:"Tuition",attendance:"Attendance",exams:"Examination Timetable",announcements:"Announcements",promotion:"Promotion"}[id];window.scrollTo({top:0,behavior:"smooth"})}
function renderAll(){renderStats();renderStudents();fillStudentSelects();renderFees();renderAttendance();renderExams();renderAnnouncements();renderPromotion();}
function renderStats(){
$("statStudents").textContent=students.filter(s=>s.status==="Active").length;
$("statClasses").textContent=new Set(students.map(s=>s.grade+" "+s.section)).size;
$("statFees").textContent="$"+students.reduce((a,s)=>a+Math.max(0,s.tuitionTotal-s.tuitionPaid),0);
$("statAnnouncements").textContent=announcements.length;
}
function renderStudents(){const q=$("studentSearch").value.toLowerCase();const g=$("gradeFilter").value;const rows=students.filter(s=>(!q||[s.id,s.name,s.grade,s.section,s.parent].join(" ").toLowerCase().includes(q))&&(!g||s.grade===g));$("studentRows").innerHTML=rows.map(s=>`<tr><td>${s.id}</td><td><strong>${s.name}</strong></td><td>${s.grade}</td><td>${s.section}</td><td>${s.parent}</td><td class="status">${s.status}</td><td><div class="row-actions"><button class="icon-btn" onclick="editStudent('${s.id}')">✏️</button><button class="icon-btn" onclick="viewStudent('${s.id}')">👁</button></div></td></tr>`).join("")||`<tr><td colspan="7">No students found.</td></tr>`}
$("studentSearch").oninput=renderStudents;$("gradeFilter").onchange=renderStudents;
function fillStudentSelects(){const opts=students.map(s=>`<option value="${s.id}">${s.name} — ${s.id}</option>`).join("");["gradeStudent","feeStudent","attendanceStudent"].forEach(id=>$(id).innerHTML=opts)}
window.editStudent=function(id){const s=students.find(x=>x.id===id);openModal("Edit Student",studentForm(s))};
window.viewStudent=function(id){const s=students.find(x=>x.id===id);openModal("Student Record",`<div class="record-card"><p><strong>Student ID:</strong> ${s.id}</p><p><strong>Name:</strong> ${s.name}</p><p><strong>Grade / Section:</strong> ${s.grade} • ${s.section}</p><p><strong>Parent/Guardian:</strong> ${s.parent}</p><p><strong>Status:</strong> ${s.status}</p><p><strong>School Year:</strong> ${s.schoolYear}</p><p><strong>Teacher:</strong> ${s.teacher}</p><p><strong>Tuition:</strong> $${s.tuitionPaid} paid of $${s.tuitionTotal}</p><p><strong>Attendance:</strong> ${s.attendance.present} present / ${s.attendance.absent} absent</p></div>`) };
function studentForm(s={}){return `<form class="student-form form-grid" id="studentForm"><label>Student ID<input name="id" value="${s.id||nextId()}" ${s.id?"readonly":""}></label><label>Full Name<input name="name" value="${s.name||""}" required></label><label>Grade<select name="grade">${[7,8,9,10,11,12].map(n=>`<option ${s.grade===`Grade ${n}`?"selected":""}>Grade ${n}</option>`).join("")}</select></label><label>Section<select name="section">${["A","B","C"].map(x=>`<option ${s.section===x?"selected":""}>${x}</option>`).join("")}</select></label><label>Parent/Guardian<input name="parent" value="${s.parent||""}" required></label><label>Status<select name="status"><option ${s.status!=="Inactive"?"selected":""}>Active</option><option ${s.status==="Inactive"?"selected":""}>Inactive</option></select></label><label>School Year<input name="schoolYear" value="${s.schoolYear||"2026–2027"}"></label><label>Class Teacher<input name="teacher" value="${s.teacher||""}"></label><div class="submit-row"><button class="primary" type="submit">Save Student</button></div></form>`}
function nextId(){const nums=students.map(s=>parseInt((s.id.match(/\((\d+)\)$/)||[,0])[1]));return `0020172(${String(Math.max(...nums,0)+1).padStart(3,"0")})`}
$("addStudent").onclick=()=>openModal("Add Student",studentForm());
document.addEventListener("submit",e=>{if(e.target.id!=="studentForm")return;e.preventDefault();const f=new FormData(e.target);const obj=Object.fromEntries(f.entries());const existing=students.findIndex(s=>s.id===obj.id);obj.tuitionTotal=existing>=0?students[existing].tuitionTotal:1200;obj.tuitionPaid=existing>=0?students[existing].tuitionPaid:0;obj.attendance=existing>=0?students[existing].attendance:{present:0,absent:0};if(existing>=0)students[existing]={...students[existing],...obj};else students.push(obj);save();closeModal();renderAll();openSection("students")});
$("exportStudents").onclick=()=>{const headers=["Student ID","Name","Grade","Section","Parent/Guardian","Status"];const csv=[headers,...students.map(s=>[s.id,s.name,s.grade,s.section,s.parent,s.status])].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n");download("vfa-students.csv",csv,"text/csv")};
$("importStudents").onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.trim().split(/\r?\n/).slice(1);lines.forEach(line=>{const c=parseCSVLine(line);if(c.length>=6){students.push({id:c[0],name:c[1],grade:c[2],section:c[3],parent:c[4],status:c[5]||"Active",schoolYear:"2026–2027",teacher:"",tuitionTotal:1200,tuitionPaid:0,attendance:{present:0,absent:0}})}});save();renderAll();e.target.value=""};
function parseCSVLine(line){return line.match(/(?:[^,\"]|\"\"|\"(?:[^\"]|\")*\")+/g)?.map(v=>v.replace(/^"|"$/g,"").replaceAll('""','"'))||[]}
function renderFees(){const rows=payments.map(p=>`<tr><td>${p.studentName}</td><td>${p.period}</td><td>$${Number(p.amount).toFixed(2)}</td><td>${p.date}</td><td class="status">Paid</td></tr>`);$("feeRows").innerHTML=rows.join("")||`<tr><td colspan="5">No payments recorded in this demo yet.</td></tr>`}
$("addPayment").onclick=()=>{const id=$("feeStudent").value,amt=Number($("feeAmount").value),period=$("feePeriod").value.trim();if(!amt||!period)return alert("Enter an amount and payment period.");const s=students.find(x=>x.id===id);payments.push({studentId:id,studentName:s.name,amount:amt,period,date:new Date().toISOString().slice(0,10)});s.tuitionPaid+=amt;save();$("feeAmount").value="";$("feePeriod").value="";renderAll()};
function renderAttendance(){$("attendanceRows").innerHTML=attendanceRecords.map(r=>`<tr><td>${r.date}</td><td>${r.studentName}</td><td class="${r.status==='present'?"success":"danger"}">${r.status==='present'?"Present":"Absent"}</td></tr>`).join("")||`<tr><td colspan="3">No daily attendance records recorded in this demo yet.</td></tr>`}
$("saveAttendance").onclick=()=>{const id=$("attendanceStudent").value,date=$("attendanceDate").value,status=$("attendanceStatus").value;if(!date)return alert("Select a date.");const s=students.find(x=>x.id===id);attendanceRecords.push({studentId:id,studentName:s.name,date,status});status==="present"?s.attendance.present++:s.attendance.absent++;save();renderAll()};
function renderExams(){$("examAdminRows").innerHTML=exams.map(x=>`<tr><td>${x.grade}</td><td>${x.section}</td><td>${x.date}</td><td>${x.subject}</td><td>${x.time}</td><td>${x.room}</td></tr>`).join("")}
$("addExam").onclick=()=>{const x={grade:$("examGrade").value,section:$("examSection").value,date:$("examDate").value,subject:$("examSubject").value.trim(),time:$("examTime").value.trim(),room:$("examRoom").value.trim()};if(!x.date||!x.subject||!x.time||!x.room)return alert("Complete the examination timetable fields.");exams.push(x);save();renderAll()};
function renderAnnouncements(){$("announcementAdminList").innerHTML=announcements.map((a,i)=>`<div class="announcement-item"><div><strong>${a.title}</strong><span>${a.date}</span><p>${a.body}</p></div><button class="icon-btn" onclick="removeAnnouncement(${i})">🗑️</button></div>`).join("")};window.removeAnnouncement=i=>{announcements.splice(i,1);save();renderAll()};
$("addAnnouncement").onclick=()=>{const title=$("announcementTitle").value.trim(),date=$("announcementDate").value,body=$("announcementBody").value.trim();if(!title||!date||!body)return alert("Complete the announcement.");announcements.unshift({title,date,body});save();$("announcementTitle").value="";$("announcementDate").value="";$("announcementBody").value="";renderAll()};
function renderPromotion(){const rank={"Grade 7":"Grade 8","Grade 8":"Grade 9","Grade 9":"Grade 10","Grade 10":"Grade 11","Grade 11":"Grade 12","Grade 12":"Graduated"};$("promotionRows").innerHTML=students.filter(s=>s.status==="Active").map(s=>`<tr><td>${s.name}</td><td>${s.grade}</td><td>${rank[s.grade]}</td><td class="status">Ready</td></tr>`).join("")};
$("promoteAll").onclick=()=>{if(!confirm("Promote all active students according to the grade progression?"))return;const rank={"Grade 7":"Grade 8","Grade 8":"Grade 9","Grade 9":"Grade 10","Grade 10":"Grade 11","Grade 11":"Grade 12","Grade 12":"Graduated"};students.forEach(s=>{if(rank[s.grade]==="Graduated"){s.status="Graduated"}else{s.grade=rank[s.grade];s.schoolYear="2027–2028"}});save();renderAll();alert("Promotion completed. Student IDs were kept unchanged.")};
$("openGradeEditor").onclick=()=>{const s=students.find(x=>x.id===$("gradeStudent").value);openModal("Report Card — "+s.name,`<p class="muted">This demo editor is a placeholder for entering the official report-card marks. The final version will load the school's subjects and grading formula.</p><div class="form-grid" style="margin-top:15px"><label>Teacher Name<input value="${s.teacher||""}" data-demo="teacher"></label><label>Class/Section<input value="${s.grade} • ${s.section}" disabled></label><div class="submit-row"><button class="primary" onclick="closeModal()">Save Demo Record</button></div></div>`) };
function openModal(title,html){$("modalTitle").textContent=title;$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")};function closeModal(){$("modal").classList.add("hidden")};$("closeModal").onclick=closeModal;$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
