const STAFF={id:"ADMIN001",password:"VFAadmin123"};
const grades=["Kindergarten",...Array.from({length:9},(_,i)=>`Grade ${i+1}`)];
const subjects=["Mathematics","English Language","Science","Social Studies","ICT","Biology","Chemistry","Physics"];
const periods={first:["1st Period","2nd Period","3rd Period","Exam"],second:["4th Period","5th Period","6th Period","Exam"]};
const defaultStudents=[
{id:"0020172(001)",name:"Andrew Johnson",grade:"Grade 9",parent:"Mary Johnson",status:"Active",schoolYear:"2026–2027",teacher:"Mrs. Sarah Johnson",tuitionTotal:1200,tuitionPaid:800},
{id:"0020172(002)",name:"Jonathan Gombay",grade:"Grade 9",parent:"Samuel Gombay",status:"Active",schoolYear:"2026–2027",teacher:"Mrs. Sarah Johnson",tuitionTotal:1200,tuitionPaid:1000},
{id:"0020172(003)",name:"Michael Smith",grade:"Grade 8",parent:"Helen Smith",status:"Active",schoolYear:"2026–2027",teacher:"Mr. David Cooper",tuitionTotal:1100,tuitionPaid:700},
{id:"0020172(004)",name:"Sarah Williams",grade:"Grade 7",parent:"James Williams",status:"Active",schoolYear:"2026–2027",teacher:"Mrs. Linda Doe",tuitionTotal:1300,tuitionPaid:1300}
];
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
let students=get("vfaAdminStudents",defaultStudents), payments=get("vfaAdminPayments",[]), attendanceRecords=get("vfaAttendance",[]), exams=get("vfaExams",[]), announcements=get("vfaAdminAnnouncements",[]), gradesData=get("vfaGrades",{}), staffAttendance=get("vfaStaffAttendance",[]), profile=get("vfaStaffProfile",{name:"Administrator",position:"School Administrator",department:"Administration",id:STAFF.id});
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("vfaAdminStudents",JSON.stringify(students));localStorage.setItem("vfaAdminPayments",JSON.stringify(payments));localStorage.setItem("vfaAttendance",JSON.stringify(attendanceRecords));localStorage.setItem("vfaExams",JSON.stringify(exams));localStorage.setItem("vfaAdminAnnouncements",JSON.stringify(announcements));localStorage.setItem("vfaGrades",JSON.stringify(gradesData));localStorage.setItem("vfaStaffAttendance",JSON.stringify(staffAttendance));localStorage.setItem("vfaStaffProfile",JSON.stringify(profile));}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
$("staffLoginForm").onsubmit=e=>{e.preventDefault();if($("staffId").value.trim()===STAFF.id&&$("staffPassword").value===STAFF.password){$("loginView").classList.add("hidden");$("adminApp").classList.remove("hidden");init();}else $("loginMessage").textContent="Incorrect Staff ID or password."};
$("toggleStaffPassword").onclick=()=>$("staffPassword").type=$("staffPassword").type==="password"?"text":"password";
$("staffLogout").onclick=()=>{$("adminApp").classList.add("hidden");$("loginView").classList.remove("hidden");$("staffPassword").value=""};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>openSection(b.dataset.section));
function openSection(id){document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.section===id));$("sectionTitle").textContent={overview:"Home",grades:"Report Cards",tuition:"Tuition",attendance:"Attendance",exams:"Examination Timetable",announcements:"Announcements",profile:"Profile"}[id];window.scrollTo({top:0,behavior:"smooth"});}
function init(){backfillStaffAbsences();renderHome();setupGrades();setupTuition();setupAttendance();setupExams();setupAnnouncements();renderProfile();}
function backfillStaffAbsences(){const d=new Date();const todayKey=today();for(let i=1;i<=30;i++){const x=new Date(d);x.setDate(d.getDate()-i);const day=x.getDay();if(day===0||day===6)continue;const date=x.toISOString().slice(0,10);if(!staffAttendance.some(r=>r.staffId===profile.id&&r.date===date)){staffAttendance.push({staffId:profile.id,date,status:"Absent",time:"—"});}}save();}
function today(){return new Date().toISOString().slice(0,10)}
function renderHome(){const d=today();$("todayLabel").textContent=new Date(d+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});$("checkinDate").textContent=$("todayLabel").textContent;const rec=staffAttendance.find(r=>r.staffId===profile.id&&r.date===d);$("staffCheckIn").disabled=!!rec;$("staffCheckIn").innerHTML=rec?'<span class="check-box">✓</span><span>PRESENT — CHECKED IN</span>':'<span class="check-box">☐</span><span>MARK ME PRESENT</span>';$("checkinStatus").textContent=rec?`Checked in at ${rec.time}. Your attendance has been recorded.`:"You have not checked in today.";const mine=staffAttendance.filter(r=>r.staffId===profile.id).sort((a,b)=>b.date.localeCompare(a.date));$("myPresent").textContent=mine.filter(r=>r.status==="Present").length;$("myAbsent").textContent=mine.filter(r=>r.status==="Absent").length;$("myLate").textContent=mine.filter(r=>r.status==="Late").length;$("staffAttendanceRows").innerHTML=mine.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.time||"—")}</td><td class="${r.status==='Present'?'success':r.status==='Late'?'warning':'danger'}">${esc(r.status)}</td></tr>`).join("")||'<tr><td colspan="3">No staff attendance recorded yet.</td></tr>'}
$("staffCheckIn").onclick=()=>{const d=today();if(staffAttendance.some(r=>r.staffId===profile.id&&r.date===d))return;staffAttendance.push({staffId:profile.id,date:d,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),status:"Present"});save();renderHome()};
function setupGrades(){ $("gradeClass").innerHTML=grades.map(g=>`<option>${g}</option>`).join("");$("gradeSubject").innerHTML=subjects.map(s=>`<option>${s}</option>`).join("");$("gradeSemester").onchange=updatePeriods;$("gradePeriod").onchange=renderGradeRows;$("gradeClass").onchange=renderGradeRows;$("gradeSubject").onchange=renderGradeRows;$("gradeSearch").oninput=renderGradeRows;updatePeriods();$("saveAllGrades").onclick=saveGrades;$("editClassStudents").onclick=editClassStudents;}
function updatePeriods(){$("gradePeriod").innerHTML=periods[$("gradeSemester").value].map(p=>`<option>${p}</option>`).join("");renderGradeRows()}
function gradeKey(studentId){return `${studentId}|${$("gradeSubject").value}|${$("gradePeriod").value}`}
function renderGradeRows(){const cls=$("gradeClass").value,q=$("gradeSearch").value.toLowerCase();const list=students.filter(s=>s.grade===cls&&s.status!=="Inactive"&&(!q||`${s.name} ${s.id}`.toLowerCase().includes(q)));$("gradeEntryRows").innerHTML=list.map(s=>{const k=gradeKey(s.id),v=gradesData[k]??"";return `<tr><td>${esc(s.id)}</td><td><strong>${esc(s.name)}</strong></td><td><input class="grade-input" data-id="${esc(s.id)}" value="${esc(v)}" inputmode="decimal" min="0" max="100" type="number"></td><td>${v!==""?'<span class="success">Saved</span>':'<span class="muted">Not entered</span>'}</td></tr>`}).join("")||'<tr><td colspan="4">No students are registered in this class yet.</td></tr>'}
function saveGrades(){document.querySelectorAll(".grade-input").forEach(input=>{const v=input.value.trim(),k=gradeKey(input.dataset.id);if(v==="")delete gradesData[k];else gradesData[k]=Math.max(0,Math.min(100,Number(v)))});save();renderGradeRows();alert("Grades saved successfully.")}
function editClassStudents(){const cls=$("gradeClass").value;openModal(`Students — ${cls}`,`<p class="muted">Add or edit students in ${esc(cls)}. Student information is reused by grades, tuition and attendance.</p><div class="student-mini-list">${students.filter(s=>s.grade===cls).map(s=>`<div><span><strong>${esc(s.name)}</strong><small>${esc(s.id)}</small></span><button class="icon-btn" onclick="editStudent('${esc(s.id)}')">✏️</button></div>`).join("")||'<p class="muted">No students yet.</p>'}</div><button class="primary" onclick="editStudent('')">+ Add Student</button>`)}
window.editStudent=function(id){const s=students.find(x=>x.id===id)||{id:"",name:"",grade:$("gradeClass").value,parent:"",status:"Active"};openModal(id?"Edit Student":"Add Student",`<form id="studentForm" class="form-grid"><label>Student ID<input name="id" value="${esc(s.id||nextId())}" ${id?"readonly":""} required></label><label>Full Name<input name="name" value="${esc(s.name)}" required></label><label>Class<select name="grade">${grades.map(g=>`<option ${s.grade===g?"selected":""}>${g}</option>`).join("")}</select></label><label>Parent / Guardian<input name="parent" value="${esc(s.parent)}" required></label><label>Status<select name="status"><option ${s.status!=="Inactive"?"selected":""}>Active</option><option ${s.status==="Inactive"?"selected":""}>Inactive</option></select></label><div class="submit-row"><button class="primary" type="submit">Save Student</button></div></form>`);$("studentForm").onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const old=students.findIndex(x=>x.id===f.id);if(old>=0)students[old]={...students[old],...f};else students.push({...f,tuitionTotal:1200,tuitionPaid:0});save();closeModal();setupGrades();setupTuition();setupAttendance();alert("Student record saved.")}}
function nextId(){const n=students.map(s=>Number((s.id.match(/\((\d+)\)/)||[,0])[1])).reduce((a,b)=>Math.max(a,b),0)+1;return `0020172(${String(n).padStart(3,"0")})`}
function setupTuition(){$("feeStudent").innerHTML=students.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — ${esc(s.id)}</option>`).join("");$("feeStudent").onchange=renderTuitionCard;$("addPayment").onclick=addPayment;renderTuitionCard();renderFees()}
function renderTuitionCard(){const s=students.find(x=>x.id===$("feeStudent").value);if(!s){$("tuitionCard").innerHTML="";return}const due=Number(s.tuitionTotal||0),paid=Number(s.tuitionPaid||0),bal=Math.max(0,due-paid);$("feeDue").value=due||"";$("tuitionCard").innerHTML=`<div><span>Student</span><strong>${esc(s.name)}</strong></div><div><span>Tuition Due</span><strong>$${due.toFixed(2)}</strong></div><div><span>Paid</span><strong>$${paid.toFixed(2)}</strong></div><div><span>Balance</span><strong>$${bal.toFixed(2)}</strong></div><div><span>Status</span><strong class="${bal===0?'success':'warning'}">${bal===0?'PAID':paid===0?'UNPAID':'BALANCE DUE'}</strong></div>`}
function addPayment(){const s=students.find(x=>x.id===$("feeStudent").value),due=Number($("feeDue").value),amt=Number($("feeAmount").value),period=$("feePeriod").value.trim();if(!s||due<0||!amt||!period)return alert("Enter the tuition due, payment amount and payment period.");s.tuitionTotal=due;s.tuitionPaid=Number(s.tuitionPaid||0)+amt;payments.unshift({studentId:s.id,studentName:s.name,period,amount:amt,date:today(),balance:Math.max(0,due-s.tuitionPaid)});save();$("feeAmount").value="";$("feePeriod").value="";renderTuitionCard();renderFees()}
function renderFees(){const rows=payments.map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(p.studentName)}</td><td>${esc(p.period)}</td><td>$${Number(p.amount).toFixed(2)}</td><td>$${Number(p.balance||0).toFixed(2)}</td><td class="${Number(p.balance||0)===0?'success':'warning'}">${Number(p.balance||0)===0?'Paid':'Balance Due'}</td></tr>`);$("feeRows").innerHTML=rows.join("")||'<tr><td colspan="6">No payments recorded yet.</td></tr>'}
function setupAttendance(){$("attendanceClass").innerHTML=grades.map(g=>`<option>${g}</option>`).join("");$("attendanceClass").onchange=fillAttendanceStudents;$("attendanceStudent").onchange=renderStudentAttendanceCard;$("attendanceDate").value=today();$("saveAttendance").onclick=saveAttendance;fillAttendanceStudents();renderAttendance()}
function fillAttendanceStudents(){const cls=$("attendanceClass").value;$("attendanceStudent").innerHTML=students.filter(s=>s.grade===cls).map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — ${esc(s.id)}</option>`).join("");renderStudentAttendanceCard();renderAttendance()}
function saveAttendance(){const id=$("attendanceStudent").value,date=$("attendanceDate").value,status=$("attendanceStatus").value,s=students.find(x=>x.id===id);if(!s||!date)return alert("Select a student and date.");attendanceRecords=attendanceRecords.filter(r=>!(r.studentId===id&&r.date===date));attendanceRecords.unshift({studentId:id,studentName:s.name,grade:s.grade,date,status});save();renderStudentAttendanceCard();renderAttendance();}
function renderAttendance(){$("attendanceRows").innerHTML=attendanceRecords.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.studentName)}</td><td>${esc(r.grade)}</td><td class="${r.status==='present'?'success':r.status==='late'?'warning':'danger'}">${r.status==='present'?'Present':r.status==='late'?'Late':'Absent'}</td></tr>`).join("")||'<tr><td colspan="4">No attendance records yet.</td></tr>'}
function renderStudentAttendanceCard(){const s=students.find(x=>x.id===$("attendanceStudent").value);if(!s){$("studentAttendanceCard").innerHTML="";return}const rows=attendanceRecords.filter(r=>r.studentId===s.id),p=rows.filter(r=>r.status==='present').length,a=rows.filter(r=>r.status==='absent').length,l=rows.filter(r=>r.status==='late').length;$("studentAttendanceCard").innerHTML=`<div><span>${esc(s.name)}</span><strong>${esc(s.grade)}</strong></div><div><span>Present</span><strong>${p}</strong></div><div><span>Absent</span><strong>${a}</strong></div><div><span>Late</span><strong>${l}</strong></div>`}
function setupExams(){$("examGrade").innerHTML=grades.filter(g=>g!=="Kindergarten").map(g=>`<option>${g}</option>`).join("");$("addExam").onclick=addExam;renderExams()}
function addExam(){const x={id:Date.now(),grade:$("examGrade").value,date:$("examDate").value,subject:$("examSubject").value.trim(),time:$("examTime").value.trim(),room:$("examRoom").value.trim()};if(!x.date||!x.subject||!x.time||!x.room)return alert("Complete the examination timetable fields.");exams.push(x);save();["examDate","examSubject","examTime","examRoom"].forEach(id=>$(id).value="");renderExams()}
function renderExams(){$("examAdminRows").innerHTML=exams.map(x=>`<tr><td>${esc(x.grade)}</td><td>${esc(x.date)}</td><td>${esc(x.subject)}</td><td>${esc(x.time)}</td><td>${esc(x.room)}</td><td><button class="icon-btn" onclick="removeExam(${x.id})">🗑️</button></td></tr>`).join("")||'<tr><td colspan="6">No examinations published yet.</td></tr>'}
window.removeExam=id=>{exams=exams.filter(x=>x.id!==id);save();renderExams()};
function setupAnnouncements(){$("announcementDate").value=today();$("addAnnouncement").onclick=addAnnouncement;renderAnnouncements()}
function addAnnouncement(){const title=$("announcementTitle").value.trim(),date=$("announcementDate").value,audience=$("announcementAudience").value,body=$("announcementBody").value.trim();if(!title||!date||!body)return alert("Complete the announcement.");announcements.unshift({id:Date.now(),title,date,audience,body});save();$("announcementTitle").value="";$("announcementBody").value="";renderAnnouncements()}
function renderAnnouncements(){$("announcementAdminList").innerHTML=announcements.map(a=>`<div class="announcement-item"><div><strong>${esc(a.title)}</strong><span>${esc(a.date)} • ${esc(a.audience)}</span><p>${esc(a.body)}</p></div><button class="icon-btn" onclick="removeAnnouncement(${a.id})">🗑️</button></div>`).join("")||'<p class="muted">No announcements published yet.</p>'}
window.removeAnnouncement=id=>{announcements=announcements.filter(a=>a.id!==id);save();renderAnnouncements()};
function renderProfile(){$("profileName").textContent=profile.name;$("profilePosition").textContent=profile.position;$("profileId").textContent=profile.id;$("profileDepartment").textContent=profile.department;$("idCardName").textContent=profile.name;$("idCardPosition").textContent=profile.position;$("idCardId").textContent=profile.id}
$("editProfile").onclick=()=>{openModal("Edit Staff Profile",`<form id="profileForm" class="form-grid"><label>Full Name<input name="name" value="${esc(profile.name)}" required></label><label>Staff ID<input name="id" value="${esc(profile.id)}" readonly></label><label>Position<input name="position" value="${esc(profile.position)}" required></label><label>Department<input name="department" value="${esc(profile.department)}" required></label><div class="submit-row"><button class="primary" type="submit">Save Profile</button></div></form>`);$("profileForm").onsubmit=e=>{e.preventDefault();profile={...profile,...Object.fromEntries(new FormData(e.target))};save();renderProfile();renderHome();closeModal()}}
$("printIdCard").onclick=()=>window.print();
function openModal(title,html){$("modalTitle").textContent=title;$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")};function closeModal(){$("modal").classList.add("hidden")};$("closeModal").onclick=closeModal;$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};


// Mobile navigation
(function(){
  const menu=document.getElementById('mobileMenu');
  const sidebar=document.querySelector('.sidebar');
  const overlay=document.getElementById('sidebarOverlay');
  if(!menu||!sidebar||!overlay) return;
  function close(){sidebar.classList.remove('mobile-open');overlay.classList.remove('show');menu.setAttribute('aria-expanded','false');}
  menu.addEventListener('click',()=>{const open=sidebar.classList.toggle('mobile-open');overlay.classList.toggle('show',open);menu.setAttribute('aria-expanded',String(open));});
  overlay.addEventListener('click',close);
  sidebar.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{if(btn!==menu) close();}));
})();
