const raw=localStorage.getItem('loggedInStudent');if(!raw){location.href='index.html';throw new Error('No student session.')};const student=JSON.parse(raw)||{},$=id=>document.getElementById(id),text=(id,v='')=>{const e=$(id);if(e)e.textContent=v??''},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
text('studentName',student.name);text('studentId',student.id);text('schoolYear',student.schoolYear);text('classValue',student.grade);text('attendanceValue',`${student.attendance?.present??0} Present / ${student.attendance?.absent??0} Absent`);text('balanceValue',student.tuition?.balance!=null?`$${student.tuition.balance}`:'');text('welcomeTitle',student.name?`Welcome, ${student.name}`:'');text('welcomeText','');text('reportName',student.name);text('reportClass',student.grade);text('reportYear',student.schoolYear);text('reportTeacher',student.teacher||'');text('reportConduct',student.reportCard?.conduct||'');
const subjects=Array.isArray(student.reportCard?.subjects)?student.reportCard.subjects:[];$('reportRows').innerHTML=subjects.map(s=>{const f=s.slice(1,5).map(Number),se=s.slice(5,9).map(Number),ft=f.reduce((a,v)=>a+(isNaN(v)?0:v),0),st=se.reduce((a,v)=>a+(isNaN(v)?0:v),0);return `<tr><td><strong>${esc(s[0])}</strong></td>${s.slice(1,5).map(v=>`<td>${esc(v)}</td>`).join('')}<td class="total-cell">${ft||''}</td>${s.slice(5,9).map(v=>`<td>${esc(v)}</td>`).join('')}<td class="total-cell">${st||''}</td></tr>`}).join('')||'<tr><td colspan="11">No grades have been entered yet.</td></tr>';
const tuition=student.tuition||{};text('totalFees',tuition.total!=null?`$${tuition.total}`:'');text('totalPaid',tuition.paid!=null?`$${tuition.paid}`:'');text('totalBalance',tuition.balance!=null?`$${tuition.balance}`:'');$('paymentRows').innerHTML=(student.payments||[]).map(p=>`<tr><td>${esc(p.period)}</td><td>${esc(p.amount)}</td><td>${esc(p.date)}</td><td>${Number(p.amount)>=0?'Recorded':''}</td></tr>`).join('')||'<tr><td colspan="4">No financial records have been entered yet.</td></tr>';
$('assignmentList').innerHTML=(student.assignments||[]).map(a=>`<div class="assignment"><h3>${esc(a.title)}</h3><p>${esc(a.subject)} • Due ${esc(a.due)}</p><p>${esc(a.body)}</p></div>`).join('')||'<p>No assignments have been published yet.</p>';$('announcementList').innerHTML=(student.announcements||[]).map(a=>`<div class="announcement"><h3>${esc(a.title)}</h3><div class="date">${esc(a.date)}</div><div>${esc(a.body)}</div></div>`).join('')||'<p>No announcements have been published yet.</p>';
const exams=student.examTimetable||[];text('examClass',student.grade||'');$('examRows').innerHTML=exams.map(r=>`<tr><td>${esc(r.date)}</td><td><strong>${esc(r.subject)}</strong></td><td>${esc(r.time)}</td><td>${esc(r.room)}</td></tr>`).join('')||'<tr><td colspan="4">No examination timetable has been published yet.</td></tr>';
$('suggestionsContent').innerHTML=(student.suggestions||[]).map(s=>`<div class="announcement"><h3>${esc(s.title)}</h3><div class="date">${esc(s.date)} • ${esc(s.from)}</div><div>${esc(s.body)}</div></div>`).join('')||'<p>No admin suggestions have been published yet.</p>';
const titles={home:'Home',grade:"Student's Grade",financial:'Financial Report',scale:'Scale Your Child',suggestions:'Admin Suggestions',assignments:'Assignments',announcements:'Announcement',exams:'Examination Timetable',profile:'Profile'};document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));function openTab(id){document.querySelectorAll('.tab-page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));text('pageTitle',titles[id]||'');window.scrollTo({top:0,behavior:'smooth'})}
$('scaleForm').addEventListener('submit',e=>{e.preventDefault();const answers=[...document.querySelectorAll('#scaleForm input:checked')].map(x=>x.value),notes=$('scaleNotes').value.trim();let all=[];try{all=JSON.parse(localStorage.getItem('vfaScaleResponses'))||[]}catch{};all.push({id:Date.now(),studentId:student.id,studentName:student.name,parent:student.parent||'',date:new Date().toISOString().slice(0,10),answers,notes});localStorage.setItem('vfaScaleResponses',JSON.stringify(all));$('scaleMessage').textContent='Feedback submitted to the school.';});
$('logout').onclick=()=>{localStorage.removeItem('loggedInStudent');location.href='index.html'};(function(){const menu=$('mobileMenu'),sidebar=document.querySelector('.sidebar'),overlay=$('sidebarOverlay');if(!menu)return;function close(){sidebar.classList.remove('mobile-open');overlay.classList.remove('show');menu.setAttribute('aria-expanded','false')}menu.addEventListener('click',()=>{const o=sidebar.classList.toggle('mobile-open');overlay.classList.toggle('show',o);menu.setAttribute('aria-expanded',String(o))});overlay.addEventListener('click',close);sidebar.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',close))})();
