(async()=>{
 const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
 const {data:{user}}=await vfaSupabase.auth.getUser();
 if(!user){location.href="index.html";return;}
 const {data:student,error}=await vfaSupabase.from("students").select("*, classes:class_id(name), staff:sponsor_id(full_name)").eq("auth_user_id",user.id).maybeSingle();
 if(error||!student||!student.is_active){await vfaSupabase.auth.signOut();location.href="index.html";return;}
 const fresh={dbId:student.id,id:student.student_code,name:student.full_name,grade:student.classes?.name||"",schoolYear:student.school_year||"",sponsor:student.staff?.full_name||"—",parent:student.parent_name||"",parentPhone:student.parent_phone||"",idCard:student.id_card_path||""};
 const [{data:subjects},{data:periods},{data:grades},{data:results},{data:finance},{data:exams},{data:assignments},{data:announcements},{data:suggestions},{data:scaleSettings}]=await Promise.all([
  vfaSupabase.from("subjects").select("id,name"),vfaSupabase.from("academic_periods").select("id,semester,period_name,sort_order").order("sort_order"),vfaSupabase.from("grades").select("score,subject_id,period_id").eq("student_id",fresh.dbId),vfaSupabase.from("student_period_results").select("average,rank,conduct,period_id").eq("student_id",fresh.dbId),vfaSupabase.from("financial_records").select("payment_date,payment_period,amount_paid,balance,amount_due").eq("student_id",fresh.dbId).order("payment_date"),vfaSupabase.from("exam_timetable").select("exam_date,start_time,end_time,room,subject_id,class_id").eq("class_id",student.class_id).order("exam_date"),vfaSupabase.from("assignments").select("title,description,due_date,class_id,subject_id,created_at").or(`class_id.eq.${student.class_id},class_id.is.null`).order("created_at",{ascending:false}),vfaSupabase.from("announcements").select("title,message,target_class_id,publish_to_all,created_at").or(`target_class_id.eq.${student.class_id},target_class_id.is.null`).order("created_at",{ascending:false}),vfaSupabase.from("admin_suggestions").select("title,message,target_class_id,created_at").or(`target_class_id.eq.${student.class_id},target_class_id.is.null`).order("created_at",{ascending:false}),vfaSupabase.from("scale_settings").select("statements").eq("id",1).maybeSingle()
 ]);
 const subById=Object.fromEntries((subjects||[]).map(x=>[x.id,x.name])), perById=Object.fromEntries((periods||[]).map(x=>[x.id,x]));
 $("studentName").textContent=fresh.name;$("studentId").textContent=fresh.id;$("schoolYear").textContent=fresh.schoolYear;$("classValue").textContent=fresh.grade;$("welcomeText").textContent=`Welcome, ${fresh.name}`;
 const due=(finance||[]).reduce((a,r)=>a+Number(r.amount_due||0),0),paid=(finance||[]).reduce((a,r)=>a+Number(r.amount_paid||0),0),balance=Math.max(0,due-paid);$("totalFees").textContent=`$${due.toFixed(2)}`;$("totalPaid").textContent=`$${paid.toFixed(2)}`;$("totalBalance").textContent=`$${balance.toFixed(2)}`;$("balanceValue").textContent=`$${balance.toFixed(2)}`;$("paymentRows").innerHTML=(finance||[]).map(r=>`<tr><td>${esc(r.payment_date)}</td><td>${esc(r.payment_period||"")}</td><td>$${Number(r.amount_paid||0).toFixed(2)}</td><td>$${Number(r.balance||0).toFixed(2)}</td></tr>`).join("")||'<tr><td colspan="4">No financial records available.</td></tr>';
 const periodsByName=Object.fromEntries((periods||[]).map(p=>[p.period_name,p]));const subNames=(subjects||[]).map(s=>s.name), gradeMap=Object.fromEntries((grades||[]).map(g=>[`${g.subject_id}|${g.period_id}`,g.score]));
 const first=["1st Period","2nd Period","3rd Period","Exam"],second=["4th Period","5th Period","6th Period","Exam"],all=[...first,...second];
 $("reportStudentName").textContent=fresh.name;$("reportStudentId").textContent=fresh.id;$("reportClass").textContent=fresh.grade;$("reportSponsor").textContent=fresh.sponsor;$("reportYear").textContent=fresh.schoolYear;
 $("reportRows").innerHTML=subNames.map(sub=>{const sid=(subjects||[]).find(x=>x.name===sub)?.id;const vals=all.map(p=>gradeMap[`${sid}|${periodsByName[p]?.id}`]??"");const f=vals.slice(0,4).reduce((a,v)=>a+Number(v||0),0),s=vals.slice(4).reduce((a,v)=>a+Number(v||0),0);return `<tr><td><strong>${esc(sub)}</strong></td>${vals.slice(0,4).map(v=>`<td>${esc(v)}</td>`).join("")}<td><strong>${f||""}</strong></td>${vals.slice(4).map(v=>`<td>${esc(v)}</td>`).join("")}<td><strong>${s||""}</strong></td></tr>`}).join("");
 const resultByPeriod=Object.fromEntries((results||[]).map(r=>[r.period_id,r]));$("reportSummaryRows").innerHTML=`<tr class="summary-row"><th>Average</th>${all.map(p=>`<td>${esc(resultByPeriod[periodsByName[p]?.id]?.average??"")}</td>`).join("")}<td></td><td></td></tr><tr class="summary-row"><th>Rank</th>${all.map(p=>`<td>${esc(resultByPeriod[periodsByName[p]?.id]?.rank??"")}</td>`).join("")}<td></td><td></td></tr>`;const conducts=all.map(p=>resultByPeriod[periodsByName[p]?.id]?.conduct).filter(Boolean);$("reportConduct").textContent=conducts.join(" • ")||"—";
 const ann=(announcements||[]).map(a=>({title:a.title,body:a.message,date:a.created_at?.slice(0,10)||""}));$("homeAnnouncements").innerHTML=ann.slice(0,2).map(a=>`<div class="announcement"><h3>${esc(a.title)}</h3><div class="date">${esc(a.date)}</div><div>${esc(a.body)}</div></div>`).join("")||"<p>No announcements available.</p>";$("announcementList").innerHTML=ann.map(a=>`<div class="announcement"><h3>${esc(a.title)}</h3><div class="date">${esc(a.date)}</div><div>${esc(a.body)}</div></div>`).join("")||"<p>No announcements available.</p>";
 const asg=(assignments||[]).map(a=>({title:a.title,body:a.description||"",due:a.due_date||"",subject:subById[a.subject_id]||""}));$("assignmentCount").textContent=asg.length;$("assignmentList").innerHTML=asg.map(a=>`<div class="announcement"><h3>${esc(a.title)}</h3><div class="date">${esc(a.subject)} • Due ${esc(a.due)}</div><div>${esc(a.body)}</div></div>`).join("")||"<p>No assignments available.</p>";
 const sug=(suggestions||[]).map(a=>({title:a.title,body:a.message,date:a.created_at?.slice(0,10)||""}));$("suggestionList").innerHTML=sug.map(a=>`<div class="announcement"><h3>${esc(a.title)}</h3><div class="date">${esc(a.date)}</div><div>${esc(a.body)}</div></div>`).join("")||"<p>No suggestions from administration yet.</p>";
 $("examClassTitle").textContent=fresh.grade||"Examination Timetable";$("examRows").innerHTML=(exams||[]).map(e=>`<tr><td>${esc(e.exam_date||"")}</td><td><strong>${esc(subById[e.subject_id]||"")}</strong></td><td>${esc([e.start_time,e.end_time].filter(Boolean).join(" - "))}</td><td>${esc(e.room||"")}</td></tr>`).join("")||'<tr><td colspan="4">No examination timetable has been published for your class.</td></tr>';
 const statements=(Array.isArray(scaleSettings?.statements)&&scaleSettings.statements.length===5)?scaleSettings.statements.map(x=>String(x||"")): ["Shows good effort","Completes assignments","Participates in class","Works well with others","Needs additional academic support"];
 $("scaleStatements").innerHTML=statements.map((text,i)=>`<label><input type="checkbox" value="${esc(text)}"> ${esc(text)}</label>`).join("");
 $("scaleForm").onsubmit=async e=>{e.preventDefault();const checks=[...e.target.querySelectorAll('input[type="checkbox"]:checked')].map(x=>x.value),note=$("scaleNote").value.trim();if(!checks.length&&!note){$("scaleMessage").textContent="Select at least one statement or enter a note.";return;}const {error}=await vfaSupabase.from("scale_your_child").insert({student_id:fresh.dbId,response:{checks,note,reviewed:false}});$("scaleMessage").textContent=error?"Could not send response. Please try again.":"Your response was sent to the school administration.";if(!error)e.target.reset();};
 const titles={home:"Home",grades:"Student's Grade",finance:"Financial Report",scale:"Scale Your Child",suggestions:"Admin Suggestions",assignments:"Assignments",announcements:"Announcements",exams:"Examination Timetable",profile:"Profile"};document.querySelectorAll(".nav-button").forEach(b=>b.addEventListener("click",()=>openTab(b.dataset.tab)));function openTab(id){document.querySelectorAll(".tab-page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));$("pageTitle").textContent=titles[id];window.scrollTo({top:0,behavior:"smooth"});}
 $("logout").onclick=async()=>{await vfaSupabase.auth.signOut();localStorage.removeItem("loggedInStudent");location.href="index.html"};
 (function(){const menu=$("mobileMenu"),sidebar=document.querySelector(".sidebar"),overlay=$("sidebarOverlay");if(!menu||!sidebar||!overlay)return;function close(){sidebar.classList.remove("mobile-open");overlay.classList.remove("show");menu.setAttribute("aria-expanded","false")}menu.onclick=()=>{const open=sidebar.classList.toggle("mobile-open");overlay.classList.toggle("show",open);menu.setAttribute("aria-expanded",String(open))};overlay.onclick=close;sidebar.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{if(btn!==menu)close()}));})();
 const preview=$("studentIdCardPreview");if(preview)preview.innerHTML=fresh.idCard?`<img src="${esc(fresh.idCard)}" alt="Student ID card">`:`<p class="muted">No ID card has been uploaded yet.</p>`;
})().catch(err=>{console.error(err);location.href="index.html";});
