const raw=localStorage.getItem('loggedInStudent');if(!raw){location.href='index.html'}
const student=JSON.parse(raw),$=id=>document.getElementById(id);
$('studentName').textContent=student.name;$('studentId').textContent=student.id;$('schoolYear').textContent=student.schoolYear;$('classValue').textContent=`${student.grade} • Section ${student.section}`;$('attendanceValue').textContent=`${student.attendance.present} Present / ${student.attendance.absent} Absent`;$('balanceValue').textContent=`$${student.tuition.balance}`;
$('reportName').textContent=student.name;$('reportClass').textContent=`${student.grade} / Section ${student.section}`;$('reportYear').textContent=student.schoolYear;$('reportTeacher').textContent=student.teacher;$('avg1').textContent=student.reportCard.term1Average;$('avg2').textContent=student.reportCard.term2Average;$('rank1').textContent=student.reportCard.term1Rank;$('rank2').textContent=student.reportCard.term2Rank;
$('totalFees').textContent=`$${student.tuition.total}`;$('totalPaid').textContent=`$${student.tuition.paid}`;$('totalBalance').textContent=`$${student.tuition.balance}`;$('presentCount').textContent=student.attendance.present;$('absentCount').textContent=student.attendance.absent;$('idName').textContent=student.name;$('idNumber').textContent=student.id;$('idClass').textContent=`${student.grade} • Section ${student.section}`;$('idYear').textContent=student.schoolYear;
$('reportRows').innerHTML=student.reportCard.subjects.map(s=>`<tr><td>${s[0]}</td><td>${s[1]}</td><td>${s[2]}</td><td>${s[3]}</td><td>${s[4]}</td><td>${s[5]}</td><td>${s[6]}</td><td>${s[7]}</td><td>${s[8]}</td><td>${s[9]}</td><td>${s[10]}</td></tr>`).join('');
const payments=[['1st Term','$200','September 5, 2026','Paid'],['2nd Term','$200','October 4, 2026','Paid'],['3rd Term','$200','November 8, 2026','Paid'],['4th Term','$200','January 12, 2027','Paid'],['5th Term','$200','February 10, 2027','Pending'],['6th Term','$200','March 10, 2027','Pending']];$('paymentRows').innerHTML=payments.map(p=>`<tr><td>${p[0]}</td><td>${p[1]}</td><td>${p[2]}</td><td class="${p[3]==='Paid'?'status-paid':'status-pending'}">${p[3]}</td></tr>`).join('');
const examTimetable=[['October 12, 2026','Mathematics','9:00 AM – 11:00 AM','Room 4'],['October 14, 2026','English Language','9:00 AM – 11:00 AM','Room 4'],['October 16, 2026','Biology','1:00 PM – 3:00 PM','Science Lab'],['October 19, 2026','Physics','9:00 AM – 11:00 AM','Room 4']];$('examRows').innerHTML=examTimetable.map(r=>`<tr><td>${r[0]}</td><td><strong>${r[1]}</strong></td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('');$('homeAnnouncements').innerHTML=student.announcements.slice(0,2).map(a=>`<div class="announcement"><h3>${a.title}</h3><div class="date">${a.date}</div><div>${a.body}</div></div>`).join('');$('announcementList').innerHTML=student.announcements.map(a=>`<div class="announcement"><h3>${a.title}</h3><div class="date">${a.date}</div><div>${a.body}</div></div>`).join('');
const titles={home:'Home',report:'Report Card',tuition:'Tuition & Fees',attendance:'Attendance',exams:'Examination Timetable',announcements:'Announcements',profile:'Profile'};
document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));document.querySelector('[data-open="announcements"]').addEventListener('click',()=>openTab('announcements'));
function openTab(id){document.querySelectorAll('.tab-page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$('pageTitle').textContent=titles[id];window.scrollTo({top:0,behavior:'smooth'})}
$('logout').addEventListener('click',()=>{localStorage.removeItem('loggedInStudent');location.href='index.html'});
